version: '3'
x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.3.3}
  restart: always
  environment:
    &airflow-common-env
    LOAD_EX: n
    _AIRFLOW_DB_MIGRATE: "true"
    _AIRFLOW_WWW_USER_CREATE: "true"
    _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USER_USERNAME}
    _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_USER_PASSWORD}
    ENGINE_CONNECT: mysql+mysqlconnector://${MYSQL_ROOT_USER}:${MYSQL_ROOT_PASSWORD}@mysql:3306/etl_db
    AIRFLOW_MYSQL_USER: ${MYSQL_ROOT_USER}
    AIRFLOW_MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    AIRFLOW_PROJECT_ID: ${GCP_PROJECT_ID}
    AIRFLOW_DATASET_ID: ${GCP_DATASET_ID}
    AIRFLOW_TABLE_ID: ${GCP_TABLE_ID}
    AIRFLOW__WEBSERVER__BASE_URL: http://nginx/airflow
    # AIRFLOW__CORE__EXECUTOR: LocalExecutor

services:

  airflow_webserver:
    <<: *airflow-common
    restart: always
    command: >
      bash -c "pip install mysql-connector-python && airflow db upgrade && airflow scheduler -D && airflow webserver"
    # ports:
    #   - "8080:8080"
    environment:
      <<: *airflow-common-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      - mysql
      - phpmyadmin

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_ABSOLUTE_URI=http://nginx/pma
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - mysql
      - phpmyadmin
      - airflow_webserver

volumes: #define our mysql volume used above
    mysql-data:
